-- Database initialization scripts for MySQL
-- Note: As per constraints, do NOT modify existing schema.
-- This file is for configuring future docker initializations or testing.

CREATE DATABASE IF NOT EXISTS document_centralizer;
USE document_centralizer;

-- Schema tables should be generated by Hibernate/JPA auto-ddl if enabled.
